
FROM postgres:12.1-alpine

ARG CSV=/var/temp/data

LABEL Author="William Luo"
LABEL repo="https://www.github.com/gluo7777"

# Uncomment if building directly
ENV POSTGRES_DB loginapp
ENV POSTGRES_USER loginapp
ENV POSTGRES_PASS supersecretlogin

# Temp
RUN mkdir -p ${CSV}
# Scripts in this directory will be executed when container launches
COPY *.sql /docker-entrypoint-initdb.d/
COPY data ${CSV}

RUN echo "Contents of ${CSV}"
RUN ls -alR ${CSV}

RUN echo "Contents of docker-entrypoint-initdb.d"
RUN ls -alR /docker-entrypoint-initdb.d

EXPOSE 5432