version: '3'
services:
    login-ui:
        image: loginui:v1
        build:
            context: ./LoginUI
            dockerfile: DockerFile
        ports: 
            - "80:3000"
        depends_on: 
            - login-server
    login-server:
        image: loginserver:v1
        build: 
            context: ./LoginServer
            dockerfile: DockerFile
        networks: 
            - service
            - backend
        ports: 
            - "80:9090"
        depends_on: 
            - redis
            - postgres
    redis:
        image: redis:v1
        build:
            context: ./LoginCache
            dockerfile: DockerFile
        networks: 
            - service
        volumes: 
            - cache:/data
    postgres:
        image: postgres:v1
        build: 
            context: ./LoginDB
            dockerfile: DockerFile
            args: 
                CSV: /var/temp/data
        volumes: 
            - postgres:/var/lib/postgresql/data
        networks: 
            - backend
        environment: 
            POSTGRES_DB: loginapp
            POSTGRES_USER: loginapp
            POSTGRES_PASS: supersecretlogin
volumes: 
    postgres:
    cache:
networks: 
    backend:
    service: