version: '3'
services: 
    login-server:
        image: loginserver:v0
        build: 
            context: ./LoginServer
            dockerfile: DockerFile
        networks: 
            - backend
        ports: 
            - "80:9090"
        depends_on: 
            - postgres
    postgres:
        image: postgres:v0
        build: 
            context: ./LoginDB
            dockerfile: DockerFile
            args: 
                CSV: /var/temp/data
        volumes: 
            - postgres:/var/lib/postgresql/data
        networks: 
            - backend
        ports: 
            - "5432:5432"
        environment: 
            POSTGRES_DB: loginapp
            POSTGRES_USER: loginapp
            POSTGRES_PASS: supersecretlogin
volumes: 
    postgres:
networks: 
    backend: