### Build Variables ###
ARG WORKDIR=/home/app
ARG SETTING=${WORKDIR}/settings-docker.xml
ARG PLUGIN_VERSION=3.1.0
ARG PORT=9090

### Build Stage ###
FROM maven:3.6-jdk-11-slim AS build
ARG WORKDIR
ARG SETTING
ARG PLUGIN_VERSION

WORKDIR ${WORKDIR}

### Cache Build Dependencies ###
COPY pom.xml settings-docker.xml ${WORKDIR}/
RUN mvn -B -s ${SETTING} org.apache.maven.plugins:maven-dependency-plugin:${PLUGIN_VERSION}:go-offline

### Build Source Code ###
COPY src src
RUN mvn -B -s ${SETTING} --offline clean package

### Package Stage ###
FROM openjdk:11.0.5-jre AS package
ARG WORKDIR
ARG PORT

COPY --from=build ${WORKDIR}/target/server-*.jar /usr/local/lib/app.jar
EXPOSE ${PORT}
ENTRYPOINT [ "java", "-jar", "/usr/local/lib/app.jar"]